"""Render a validated plan as Markdown. The same data also goes out as JSON."""

from __future__ import annotations

import re
from typing import Iterable, List, Sequence, Set

from .bundle import ContextBundle
from .risk import HIGH_AT, MEDIUM_AT, level_for
from .schema import TestCase, TestPlan

_FACT = re.compile(r"^F\d+$")
_ORDER = {"P0": 0, "P1": 1, "P2": 2}


def _cell(text: str) -> str:
    return re.sub(r"\s+", " ", str(text)).replace("|", "\\|").strip()


def _table(header: Sequence[str], rows: Iterable[Sequence[str]]) -> List[str]:
    lines = ["| " + " | ".join(header) + " |", "|" + "|".join("---" for _ in header) + "|"]
    lines += ["| " + " | ".join(_cell(c) for c in row) + " |" for row in rows]
    return lines


def _num(ident: str) -> int:
    digits = re.sub(r"\D", "", ident)
    return int(digits) if digits else 0


def _factor(factor) -> str:
    refs = ", ".join(factor.fact_ids[:3])
    inner = f"{refs} - {factor.detail}" if refs and factor.detail else (refs or factor.detail)
    return f"{factor.name} +{factor.points}" + (f" ({inner})" if inner else "")


def sorted_cases(plan: TestPlan) -> List[TestCase]:
    return sorted(plan.cases, key=lambda c: (_ORDER.get(c.priority, 9), _num(c.id)))


def cited_facts(plan: TestPlan, bundle: ContextBundle) -> List[str]:
    seen: Set[str] = set()
    refs: List[str] = []
    known = bundle.risk_by_id()
    for r in plan.risks:
        refs += r.evidence
        base = known.get(r.id)
        if base:
            for factor in base.likelihood_factors + base.impact_factors:
                refs += factor.fact_ids
    for c in plan.cases:
        refs += c.evidence
    for x in plan.regression_scope:
        refs += x.evidence
    for q in plan.open_questions:
        refs += q.evidence
    for ref in refs:
        if _FACT.match(ref) and ref not in seen:
            seen.add(ref)
    return sorted(seen, key=_num)


def render_markdown(plan: TestPlan, bundle: ContextBundle) -> str:
    meta = plan.meta
    errors = [v for v in plan.validation if v.get("severity") == "error"]
    warnings = [v for v in plan.validation if v.get("severity") != "error"]
    out: List[str] = [f"# Test plan: {bundle.title}", ""]
    out.append(
        f"> **Draft.** Generated by `{meta.get('generator', '?')}` ({meta.get('model', '?')}) "
        f"on {meta.get('created', '?')}. Nothing here has been run. A person should review and "
        "edit it before it is used."
    )
    if errors:
        out += [
            ">",
            f"> **{len(errors)} unresolved check failure(s).** Parts of this plan are not grounded "
            "in the evidence. See section 9.",
        ]

    # 1 ------------------------------------------------------------------------------------
    out += ["", "## 1. Summary and scope", "", plan.summary.text, ""]
    out.append(f"**Change class:** {plan.summary.change_class}")
    if plan.summary.in_scope:
        out += ["", "**In scope**", ""] + [f"- {x}" for x in plan.summary.in_scope]
    if plan.summary.out_of_scope:
        out += ["", "**Out of scope**", ""] + [f"- {x}" for x in plan.summary.out_of_scope]

    # 2 ------------------------------------------------------------------------------------
    out += ["", "## 2. Risk assessment", ""]
    if plan.risks:
        rows = []
        for r in sorted(plan.risks, key=lambda r: (-r.score, _num(r.id))):
            adj = r.adjustment
            note = (
                f"{adj.likelihood_delta:+d} likelihood, {adj.impact_delta:+d} impact: {adj.reason}"
                if (adj.likelihood_delta or adj.impact_delta)
                else "-"
            )
            rows.append(
                [
                    r.id,
                    r.title,
                    str(r.likelihood),
                    str(r.impact),
                    str(r.score),
                    level_for(r.score),
                    note,
                    ", ".join(r.evidence[:6]),
                ]
            )
        out += _table(
            [
                "Risk",
                "What could go wrong",
                "Likelihood",
                "Impact",
                "Score",
                "Level",
                "Adjusted",
                "Evidence",
            ],
            rows,
        )
        out += [
            "",
            "Likelihood and impact run from 1 to 5. The score is their product: "
            f"{HIGH_AT} or more is high, {MEDIUM_AT} to {HIGH_AT - 1} medium.",
            "",
            "**How the scores were reached** (computed from facts; each factor adds to a base of 1 "
            "for likelihood)",
            "",
        ]
        known = bundle.risk_by_id()
        for r in sorted(plan.risks, key=lambda r: _num(r.id)):
            base = known.get(r.id)
            if base is None:
                continue
            why_l = "; ".join(_factor(f) for f in base.likelihood_factors) or "no raising factors"
            why_i = "; ".join(_factor(f) for f in base.impact_factors) or "baseline"
            out.append(f"- {r.id}. Likelihood: {why_l}. Impact: {why_i}.")
    else:
        out.append("No risks were identified.")

    # 3 ------------------------------------------------------------------------------------
    cases = sorted_cases(plan)
    out += ["", "## 3. Test conditions", ""]
    if cases:
        rows = [
            [
                c.id,
                c.priority,
                c.title,
                c.requirement,
                c.technique,
                c.level,
                c.automation,
                c.existing_coverage,
                c.confidence,
                ", ".join(c.evidence),
            ]
            for c in cases
        ]
        out += _table(
            [
                "ID",
                "Priority",
                "Condition",
                "Requirement",
                "Technique",
                "Level",
                "Automate",
                "Existing coverage",
                "Confidence",
                "Evidence",
            ],
            rows,
        )
        detailed = [c for c in cases if c.priority in ("P0", "P1")]
        if detailed:
            out += ["", "### Steps and expected results (P0 and P1)"]
            for c in detailed:
                out += ["", f"**{c.id}: {c.title}**", ""]
                out += [f"{i}. {s}" for i, s in enumerate(c.steps, start=1)]
                out += ["", f"Expected: {c.expected}"]
                if c.requirement == "none" and c.requirement_reason:
                    out += ["", f"No criterion covers this: {c.requirement_reason}."]
                if c.confidence != "high" and c.confidence_reason:
                    out += ["", f"Confidence {c.confidence}: {c.confidence_reason}."]
    else:
        out.append("No test conditions were produced.")

    # 4 ------------------------------------------------------------------------------------
    out += ["", "## 4. Regression scope", ""]
    if plan.regression_scope:
        out += _table(
            ["Existing test", "Why re-run it", "Evidence"],
            [[x.test, x.reason, ", ".join(x.evidence)] for x in plan.regression_scope],
        )
    else:
        out.append(
            "No existing tests were linked to the change. Give the tool the repository with `--repo` to find them."
        )

    # 5 ------------------------------------------------------------------------------------
    gaps = [c for c in cases if c.existing_coverage == "none"]
    covered = len(cases) - len(gaps)
    out += ["", "## 5. Coverage gaps", ""]
    out.append(
        f"{len(gaps)} of {len(cases)} conditions have no existing test; {covered} are already exercised by one."
    )
    if gaps:
        out.append("")
        out += [f"- {c.id} ({c.priority}): {c.title}" for c in gaps]

    # 6 ------------------------------------------------------------------------------------
    out += ["", "## 6. Open questions and assumptions", ""]
    if plan.open_questions:
        out += _table(
            ["ID", "Type", "Question", "Evidence"],
            [[q.id, q.kind, q.text, ", ".join(q.evidence)] for q in plan.open_questions],
        )
    else:
        out.append("No open questions.")
    if plan.assumptions:
        out += ["", "**Assumptions**", ""] + [f"- {a}" for a in plan.assumptions]

    # 7, 8 ---------------------------------------------------------------------------------
    out += ["", "## 7. Environment and data needs", ""]
    out += [f"- {x}" for x in plan.environment_needs] or ["Nothing beyond the existing setup."]
    out += ["", "## 8. Exit criteria", ""]
    out += [f"- [ ] {x}" for x in plan.exit_criteria] or [
        "- [ ] All planned conditions have been run."
    ]

    # 9 ------------------------------------------------------------------------------------
    out += ["", "## 9. Appendix", "", "### Plan checks", ""]
    if errors or warnings:
        out += _table(
            ["Severity", "Check", "Where", "Message"],
            [
                [v["severity"], v["code"], v.get("where", ""), v["message"]]
                for v in errors + warnings
            ],
        )
    else:
        out.append(
            "All checks passed: every citation resolves, every criterion has a condition, and risks match the computed scores."
        )
    ids = cited_facts(plan, bundle)
    out += ["", "### Facts cited", ""]
    if ids:
        rows = []
        for fid in ids:
            fact = bundle.facts.get(fid)
            rows.append([fid, fact.kind if fact else "?", fact.text if fact else "(unknown fact)"])
        out += _table(["Fact", "Kind", "What was found"], rows)
    else:
        out.append("No facts were cited.")
    out += [
        "",
        "### Run details",
        "",
        f"- Generator: {meta.get('generator', '?')} ({meta.get('model', '?')})",
        f"- Context as of: {bundle.meta.get('as_of', '?')}",
        f"- Context hash: {str(meta.get('bundle_sha256', ''))[:12] or 'n/a'}",
        f"- Tool version: {bundle.meta.get('tool_version', '?')}",
    ]
    if bundle.warnings:
        out += ["", "### Collector warnings", ""] + [f"- {w}" for w in bundle.warnings]
    return "\n".join(out) + "\n"
